version: '3.1'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: "+IcoKg1B530IWS+MnPXcnsFqGXvXu1T6/96GoqgL7oo="
    ports:
      - "5436:5432"
    volumes:
      - my_dbdata:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    ports:
      - "9001:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    depends_on:
      - db

volumes:
  my_dbdata:
